FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    curl \
    ca-certificates \
    python3 \
    python3-pip \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m user
RUN mkdir /home/user/app/ && mkdir /home/user/data/

ADD requirements.txt /home/user/app/
WORKDIR /home/user/app
RUN pip3 install -r requirements.txt && pip3 install mkl
ADD src /home/user/app
ADD data /home/user/data

RUN chown -R user:user /home/user/
USER user

EXPOSE 5000
ENTRYPOINT ["gunicorn", "api:app", "--workers", "4", "--bind", " 0.0.0.0:5000"]
